version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    open-pull-requests-limit: 3
    reviewers:
      - 'acellam'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    open-pull-requests-limit: 3
    reviewers:
      - 'acellam'
